version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 909277259186.drk.ecr.ap-south-1.amazonaws.com
      - REPO_URL=909277259186.drk.ecr.ap-south-1.amazonaws.com/2024-game
      - IMAGE_TAG=${echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7}
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPO_URI:$IMAGE_TAG
      - print '[{"name":"2048-container","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    imagedefinitions.json
